Two level design
microbit-foundation/python-editor-next pull request #401
Opened 2021-12-23 16:43 UTC by microbit-matt-hillsdon

Remaining issues:
- e2e
- can't "activate" the same thing twice in a row, needs a bit of a rethink, perhaps URL state is the wrong idea or it should be cleared

Maybe separate PR:
- fading background as per design for active one (just add to the effect)

2021-12-23 16:44 UTC, microbit-matt-hillsdon commented on src/documentation/common/ShowMoreButton.tsx
> +    width="max-content"
To review, feels like there's a lot here.
The font also feels lighter than in XD.

2022-01-05 11:00 UTC, microbit-matt-hillsdon commented on src/documentation/ToolkitDocumentation/ToolkitDocumentation.tsx
> +      key={urlParam.length > 0 ? 0 : 1}
Might be clearer for this to just use `anchor` now.

2022-01-05 12:07 UTC, microbit-matt-hillsdon commented on src/documentation/ToolkitDocumentation/ToolkitDocumentation.tsx
> +      key={urlParam.length > 0 ? 0 : 1}
Rewriting in terms of anchor here (and surrounding code here and in reference) improved things.

2022-01-05 12:23 UTC, microbit-matt-hillsdon commented on src/documentation/common/ShowMoreButton.tsx
> +    width="max-content"
I've dropped what I can here.
The font weight is the most significant different from the design here.

2022-01-05 12:26 UTC, microbit-matt-hillsdon commented
Visually, I still don't like "SHOW MORE" but I think we should probably merge without worrying about that and then consider options (mostly because this is holding up other PRs).

2022-01-05 12:28 UTC, microbit-matt-hillsdon commented
Spotted a spacing regression in Reference.
New:
![image](https://user-images.githubusercontent.com/44397098/148217686-a4dce2d7-c660-4284-9c32-0d5d1cc67cad.png)
Old:
![image](https://user-images.githubusercontent.com/44397098/148217702-63b0440f-dd3f-40b2-8705-67474c289be4.png)

2022-01-05 12:29 UTC, microbit-matt-hillsdon commented
Preview URL is: 

https://review-python-editor-next.microbit.org/two-level-design-2/

2022-01-05 14:11 UTC, microbit-robert requested changes
- Scrolling to reference documentation from the link in the signature help is a little inconsistent. It always scrolls, but not necessarily to the correct place (e.g. for `display.show()`, I can see a 'show less' at the top of the scroll area).
- The link in signature help for anything in `audio` only takes you to references docs level 1, and not into the audio section for some reason.
- If not already inside the relevant second level of the reference toolkit, clicking the link in the signature help a second time after scrolling has finished, appears to cause a flash/glitch in the toolkit. E.g., `display.set_pixel()`

2022-01-05 14:56 UTC, microbit-matt-hillsdon commented
There's an issue open about an issue with audio which might be related: #317

2022-01-05 15:03 UTC, microbit-matt-hillsdon commented
> * Scrolling to reference documentation from the link in the signature help is a little inconsistent. It always scrolls, but not necessarily to the correct place (e.g. for `display.show()`, I can see a 'show less' at the top of the scroll area).

I think this is #325 in "show more" form. We don't uniquely identify the overload of scroll so we expand both which can cause the offset issue. Can you reproduce this with a method that doesn't have an overload?

> * The link in signature help for anything in `audio` only takes you to references docs level 1, and not into the audio section for some reason.

I'll look at this with #317.

> * If not already inside the relevant second level of the reference toolkit, clicking the link in the signature help a second time after scrolling has finished, appears to cause a flash/glitch in the toolkit. E.g., `display.set_pixel()`

New issue:

URLs are utterly messed up! E.g. ends with `%5Bobject%20Object%5D`. We need to unwrap Anchor.

2022-01-06 10:08 UTC, microbit-matt-hillsdon commented on src/documentation/reference/ReferenceToolkit.tsx
> +  console.log({ anchor });
Unwanted debug:

```suggestion
```

2022-01-06 10:12 UTC, microbit-matt-hillsdon commented
> > * Scrolling to reference documentation from the link in the signature help is a little inconsistent. It always scrolls, but not necessarily to the correct place (e.g. for `display.show()`, I can see a 'show less' at the top of the scroll area).
> 
> I think this is #325 in "show more" form. We don't uniquely identify the overload of scroll so we expand both which can cause the offset issue. Can you reproduce this with a method that doesn't have an overload?

We could and I've fixed it with a delay so the final height of the container accounts for the show-more expand before the scroll.

> > * The link in signature help for anything in `audio` only takes you to references docs level 1, and not into the audio section for some reason.
> 
> I'll look at this with #317.

Still leaving that to look at separately.

> > * If not already inside the relevant second level of the reference toolkit, clicking the link in the signature help a second time after scrolling has finished, appears to cause a flash/glitch in the toolkit. E.g., `display.set_pixel()`
> 
> I can't make this happen.

We reproduced this and I've finally fixed it in Slide.tsx (unintentional tree structure change causing component recreation).

> New issue:
> 
> URLs are utterly messed up! E.g. ends with `%5Bobject%20Object%5D`. We need to unwrap Anchor.

This is also fixed.

I think this PR is good to go. I'll address the fading background separately.

2022-01-06 10:13 UTC, microbit-matt-hillsdon commented
> Spotted a spacing regression in Reference. New: ![image](https://user-images.githubusercontent.com/44397098/148217686-a4dce2d7-c660-4284-9c32-0d5d1cc67cad.png) Old: ![image](https://user-images.githubusercontent.com/44397098/148217702-63b0440f-dd3f-40b2-8705-67474c289be4.png)

This is also fixed.

2022-01-06 11:20 UTC, microbit-matt-hillsdon commented
One issue to look at after merge:

- If there's a CM in the Collapse then it seems to fade out but not slide up, e.g. display.scroll. Clearer if you remove the other content in the Collapse. What's going on?

2022-01-06 12:06 UTC, microbit-robert approved these changes
LGTM

2022-01-06 12:08 UTC, microbit-matt-hillsdon commented
> * If there's a CM in the Collapse then it seems to fade out but not slide up, e.g. display.scroll. Clearer if you remove the other content in the Collapse

Now #407

2022-01-06 12:16 UTC, merged